---
- hosts: all
  become: yes
  vars:
    x11_forwarding:
      - xauth
      - gnome-terminal
    build_tools:
      - autoconf
      - automake
      - libtool
      - pkg-config
      - build-essential
      - valgrind
      - cmake
      - ant
      - maven
    version_control:
      - git
    python2:
      - python
      - python-pip
      - python-dev
    python3:
      - python3
      - python3-pip
      - python3-dev
    java8:
      - openjdk-8-jdk
    ocaml:
      - m4
      - opam
  
  environment:
    JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-amd64

  tasks:

    - name: Update and upgrade packages
      block:
        - apt:
            name: aptitude
            state: present
        - shell: |
            rm -rf /var/lib/apt/lists/*
        - shell: |
            apt-get clean
        - apt:
            upgrade: full
            update_cache: yes

    - name: Install X11 forwarding
      apt:
        name: "{{ x11_forwarding }}"
        state: present

    - name: Install build tools
      apt:
        name: "{{ build_tools }}"
        state: present

    - name: Install version control systems
      apt:
        name: "{{ version_control }}"
        state: present

    - name: Install Python 2
      apt:
        name: "{{ python2 }}"
        state: present

    - name: Install Python 3
      apt:
        name: "{{ python3 }}"
        state: present

    - name: Install Java
      apt:
        name: "{{ java8 }}"
        state: present

    - name: Install Node.js 8
      block:
        - shell: |
            curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
            bash nodesource_setup.sh
            rm -f nodesource_setup.sh
        - apt:
            name: nodejs
            state: present
        - npm:
            name: npm
            global: yes
        - npm:
            name: nuclide
            global: yes
        - shell: |
            git clone https://github.com/facebook/watchman.git
            cd watchman
            git checkout v4.9.0
            ./autogen.sh
            ./configure
            make
            make install
            cd ..
            rm -rf watchman

    - name: Install OCaml
      block:
        - apt:
            name: "{{ ocaml }}"
            state: present
        - shell: |
            opam init -a -y --comp 4.05.0
            eval `opam config env`
            opam install -y utop ounit qtest yojson lwt menhir ansiterminal lambda-term coq.8.6.1
