---
- hosts: all
  become: yes
  vars:
    build_tools:
      - build-essential
      - cmake
      - ant
      - maven
    x11_forwarding:
      - xauth
      - gnome-terminal
    version_control:
      - git
    python2:
      - python
      - python-pip
      - python-dev
    python3:
      - python3
      - python3-pip
      - python3-dev
    java8:
      - openjdk-8-jdk
    ocaml:
      - m4
      - opam
  environment:
    JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-amd64

  tasks:
    
    - name: Update and upgrade packages
      block:
        - apt:
            name: aptitude
            state: present
        - shell: |
            rm -rf /var/lib/apt/lists/*
        - shell: |
            apt-get clean
        - apt:
            upgrade: full
            update_cache: yes

    - name: Install build tools
      apt: 
        name: "{{ build_tools }}" 
        state: present 
    
    - name: Install X11 Forwarding functionality
      # Should work, but doesn't :(
      # apt: 
      #   name: "{{ x11_forwarding }}"
      #   state: present
      shell: |
        apt --fix-missing install -y xauth gnome-terminal
      become: yes
      ignore_errors: yes

    - name: Install version controls
      apt: 
        name: "{{ version_control }}"
        state: present
    
    - name: Install Python 2
      apt: 
        name: "{{ python2 }}"
        state: present
        
    - name: Install Python 3
      apt: 
        name: "{{ python3 }}" 
        state: present
        
    - name: Install Java
      apt:
        name: "{{ java8 }}"
        state: present

    - name: Install Node.js 6
      block:
        - shell: |
            curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh
        - shell: |
            bash nodesource_setup.sh
        - shell: |
            rm -f nodesource_setup.sh
        - apt: 
            name: nodejs
            state: present
        - npm:
            name: npm
            global: yes
          
    - name: Install OCaml
      block:
        - apt: 
            name: "{{ ocaml }}"
            state: present
        - shell: | 
            opam init -a -y --comp 4.05.0
        - shell: |
            eval `opam config env`
        - shell: |
            opam install -y utop ounit qtest yojson lwt menhir ansiterminal lambda-term coq.8.6.1